# Amazon ECR
# expects AWS_*** in bash startup config
AWS_ACCT_ID := ${AWS_ACCT_ID}
AWS_REGION := ${AWS_REGION}
ECR_URI := $(AWS_ACCT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com

# ECR Reference
# <account_id>.dkr.ecr.<region>.amazonaws.com
# aws ecr get-login --no-include-email --region <region>
# docker build -t <image> .
# docker tag <image> <account_id>.dkr.ecr.<region>.amazonaws.com/<image>:<tag>
# docker push <account_id>.dkr.ecr.<region>.amazonaws.com/<image>:<tag>
